[local]
localhost

[mongodb]
mongodb.anu90.shop

[redis]
redis.anu90.shop

[mysql]
mysql.anu90.shop

[rabbitmq]
rabbitmq.anu90.shop

[catalogue]
catalogue.anu90.shop

[rabbitmq]
rabbitmq.anu90.shop

[user]
user.anu90.shop